# Spring Boot Configuration
server:
  port: 8080

spring:
  application:
    name: userpop-backend

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:file:./data/userpop
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Security Configuration (기본 비활성화)
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: NexHubStudioSecretKeyForJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'

# Logging
logging:
  level:
    com.nexhubstudio: DEBUG
    org.springframework.security: DEBUG
